### ISSUE TITLE
A more sophisticated shading system

### ISSUE THREAD

**Issue by cessen** [cessen/psychopath#10]
Although eventually it would be nice to support Open Shading Language, I think there is a reasonable in-between stage where Psychopath should have some reasonable shading capabilities but isn't ready yet for full OSL.

This issue is a placeholder for thinking out loud about how that in-between system might be designed.

My first thought is that a shader-network approach is probably the way to go.  But the specifics aren't clear to me yet.

**Comment by bsavery** [comment]
Reading your blog about doing the "manuka thing" of baking values into the diced micropolygons, it seems that using OSL for the texture network and maybe not the BXDF makes sense.  RenderMan and others allow OSL for texture networks but not closures, so this isn't a new idea.

BTW fun note, at some point, maybe still, Manuka was using RenderMan to dice geometry as a pre pass, in "REYES" mode.

**Comment by virtualritz** [comment]
+1. Just add support for BXDFs later and use OSL as a procedural texturing system at first.
You also get the whole texture cache/filtering for free through the OIIO dependency.

**Comment by cessen** [comment]
@bsavery Yeah, I think that could make a lot of sense.

I still want to do something other than OSL first.  Partly that's because I think building my own shading system will be a good learning experience.  And learning is a big part of my motivation for working on Psychopath in the first place.

But at this point I also just want to play with alternative shading system designs, to see if there's a better way to approach things in the context of a spectral renderer.  IIRC, OSL assumes a tristimulus model of color.  And that's great for most authored assets.  But I think it would be interesting to explore building a shading system that thinks about color in a more physically-based, spectral way, and makes fewer assumptions about the input color model(s).

There are obviously a lot of complexities that would come with that.  And it would demand a much deeper understanding of physical light and color from the user.  But it's a design space that I'd like to play with, even if it doesn't yield any practical solutions in the end.

So to be clear: I think it's likely that after doing all that, I'll just end up going with something along the lines of what you're suggesting anyway.  But I'd like to take some fun detours first. :-)

**Comment by virtualritz** [comment]
I agree that implementing your own shading system is a nice exercise but you had to do that anyway, even you integrated OSL.
OSL is just the language. The implementation of the closures is up to you since they are implemented inside the renderer and not in OSL. And you can add your own closures and/or add more parameters to the existing ones.

Two things about spectral:
1. You are mistaken that anything in the design of OSL was influenced by the fact that the actual reference implementation uses RGB under the hood and exposes that at some points in the language.
It could be a hexachrome space or wavelengths or whatever. As a shader writer you do not care.
You are not (or rather: should not be) working with individual color components. This is an implementation detail. And it could be changed in a fork of OSL (a good exercise btw.).

2. Why do you think this would demand a deeper understanding of spectral color from the user (aka: a shader writer)? Just wondering.

One of the decision that OSL made was to take the power of writing BXDFs in the language itself away from the user. Closures are black boxes to shader writers.
And if you wanted to do a good job at designing a shading subsystem for a spectral renderer, you'd copy that approach. As a shader writer I ideally want to be able to layer BXDFs and have the right thing happening. Not fiddle with wavelengths inside shaders. Been there, done that. 

What over 30 years of RenderMan Shading Language in PRMan and other renderers (RenderDotC, BMRT, Entropy, Air, 3Delight) have shown, again and again, is that all this power leads to is that users write mini renderers inside the shading system.
And then they demand more language & renderer extensions from the renderer developers to support this complexity. The class system, co-shaders etc. that Pixar added to RSL from 2005 onwards (if my memory serves me right) is a complete mess.
And I was an ignorant to support this and ask for it to be added to 3Delight in 2006.
Curiously, when that hit a dead end of complexity, in recent years, users started to resort to writing more C++ shadeops and just the whole shaders in C++. This is basically admitting complete defeat.
 
Countering this early on, OSL's design was informed by hard learned lessons from the people who worked at Pixar before and/or at places affected by this.

I would suggest to take a close look at the evolution of RenderMan SL, see how GLSL and co. are based earlier versions of this language and understand why OSL, along those lines, took a step back to support 95% of use cases well and 5% not at all (namely writing BXDFs or custom patterns in a system language).
Instead of supporting 100% and making everyone's life difficult.

Sorry about the rant. I wrote shaders for blockbuster VFX for many years for a living.  :)

**Comment by bsavery** [comment]
As one of the people who was working on RenderMan at the time, I just have to say these rants from @virtualritz make me nostalgic ;). Although I think the class based shaders and coshaders to RSL (and your subsequent pain) was more like 2010. 

Joking aside, there are some very legitimate point in there.  One is that separating TEXTURE PATTERN generation and BXDF computation can be separated and users usually shouldn't implement the latter, but it sounds like you were leaning that way from the blog posts, if you're going down the manuka vertex value approach.  

What you're talking about @cessen sounds somewhat similar mitsuba2 does with a "spectrum" type instead of a (RGB) color type.  Of course a spectrum could be even simplified to be an RGB in some cases.  But as Moritz said, you could do this by extending the types in OSL too.

**Comment by cessen** [comment]
So perhaps I should clarify first that I've always planned for the BxDFs to be implemented in the renderer, not something written in shaders.  That is indeed one of the decisions that I admire OSL for, and seems like the Right Way&#8482; to do things in a physically-based renderer.  So I think we're all on the same page there.

@virtualritz:

> You are mistaken that anything in the design of OSL was influenced by the fact that the actual reference implementation uses RGB under the hood and exposes that at some points in the language.

I think you might be misunderstanding me here.  I'm not claiming that any of OSL's really core design principles are based on RGB&mdash;I agree they're not.  What I'm saying, rather, is precisely what you've just reiterated: OSL as it is *actually implemented and documented* does assume tristimulus color as the base color model.  So I think we're at least in agreement about the basic facts here, even if not their implications.

I also agree that OSL could be forked to substitute a different color model.  But for reasons that are maybe not immediately apparent, that doesn't necessarily help as much as you might think.

As an example: one of the benefits of a spectral renderer like Psychopath is that you can support multiple different incompatible color models at once, including ones with precise spectral definitions.  For example, right now Psychopath supports both tristimulus color and color derived from the temperature of black body radiators.  These two color models cannot be mixed outside of a spectral context without losing spectral information.  To mix them outside of a spectral context, you would need to first convert the black body color to e.g. some RGB color space, and then mix in that space.  But that conversion is lossy from a spectral perspective.

It is trivial, of course, to accurately mix those color models (or any other color model, for that matter) *after* spectral sampling.  And in many spectral renderers that would be a perfectly fine way to do things: in OSL just substitute a physical spectral model in place of the current perceptual RGB model, and do all mixing with those spectrums.  However, in Psychopath all pattern generation will be done ahead of time and stored at micropolygon vertices.  This puts Psychopath in a bit of a bind, because it's not practical to store full sampled spectrums at each of those vertices.  Doing so would take up an enormous amount of memory.

This situation creates a really *interesting* design space, I think, and it's one that I would like to explore.  Some of the things I might explore could be done pretty easily by just substituting out OSL's RGB model for something else, but others not so much.

> Why do you think this would demand a deeper understanding of spectral color from the user (aka: a shader writer)? Just wondering.

It wouldn't *necessarily* demand that, but some designs might.  For example, one possible solution to the issue above would be to simply have multiple color models available in the system, but make them incompatible with each other, so you can't e.g. mix them together in a single BxDF color input.  For many users it won't be obvious why it's even *possible* for colors to ever be incompatible for mixing, and I can imagine that being very confusing and frustrating.

On the one hand, the user could just accept that restriction blindly (and probably begrudgingly), and would still be able to use the system.  But to really come to terms with it, and to know how to work with it in a way that doesn't lose spectral information, they would *at least* need to develop some appreciation for and understanding of the difference between color (which is perceptual) and light spectrums (which are physical).

I'm not claiming that these topics are *difficult* to understand.  But I don't think I'm wrong in asserting that most users of 3d rendering tech don't *currently* understand these topics well.

In any case, as I alluded to in my previous comment, I strongly suspect that in the end I'll just end up using OSL as-is anyway, and find some complementary way to manage physically based color.  But I want to play and explore other ideas first.  Psychopath isn't *that* serious of a project.  It's a playground for me to play with ideas that I find interesting.

I definitely appreciate the discussion here, and am more than happy to keep talking.  But please do keep in mind the nature of this project: it's a for-fun personal project, not a commercial enterprise with clients. :-)

**Comment by cessen** [comment]
> What over 30 years of RenderMan Shading Language in PRMan and other renderers (RenderDotC, BMRT, Entropy, Air, 3Delight) have shown, again and again [...]

As a very small aside, I'm still a bit bitter towards Pixar over the whole Exluna/Entropy thing back in 2002.  It would have been really cool to see where that company would have gone.  Although, maybe Matt Pharr wouldn't have co-written PBRT then. Hmm...

**Comment by virtualritz** [comment]
> As a very small aside, I'm still a bit bitter towards Pixar over the whole Exluna/Entropy thing back in 2002. It would have been really cool to see where that company would have gone. Although, maybe Matt Pharr wouldn't have co-written PBRT then. Hmm...

Don't be. To be honest, Entropy was based on BMRT. These renderers were never impressive. BMRT was Larry's student pet so that's ok; but Entropy should have been faster.
Even less impressive was Gelato which was GPU based and obviously must have been based, to a large degree, on Entropy code. You don't have a new offline renderer ready after less than a year if you write it from scratch (as the outcome of the lawsuit indirectly required).

I started at Rising Sun Pictures in 2005 and they used Gelato then. It was slow and required NVIDIA GPUs to be faster (don't recall if it even worked w/o a GPU). Subsurface, a key feature for a creature show (Charlotte's Web), was lacking to say the least. It had lots of bugs and it was unstable.

I made a point for them to use 3Delight which was years ahead (and also always had been a ray-tracing capable renderer, since it's birth in 1999). That turned out to be a good decision for reasons different than the fact that it was as stupid to buy GPUs to render offline faster in 2005 as it is in 2020: Gelato was discontinued briefly after that show wrapped.

I heard a story that NVIDIA once gave 75 blades to a studio in London to test Gelato. They couldn't use it because the heat these GPU blades generated made the farm's AC choke. :-P

People are great at certain things and less so at others. I think Matt writing 'the book' and Larry designing OSL was just destiny falling into places. Them writing production renderers ... I am no so sure after using theirs.

It is also just because ultimately Pixar will be forced to go fully OSL, a language designed by someone they once fucked badly not because they actually stole intellectual property but because Pixar could.

I look forward to that day because when all engines support base OSL & USD you can finally easily compare quality & speed.

**Comment by virtualritz** [comment]
> [...] in Psychopath all pattern generation will be done ahead of time and stored at micropolygon vertices. 

Interesting choice. What happens when you have a refractive object acting as a lens in front of other (diced) geometry? Will you re-dice on the fly when you see that the area the path's covers is much smaller than a micropolygon?

On that note: Houdini's Mantra does (optional) re-dicing for displacement shading. If a micropolygon get stretched beyond a certain threshold the area is re-diced locally and the displacement shader re-ran on the new grid.

**Comment by cessen** [comment]
> Interesting choice. What happens when you have a refractive object acting as a lens in front of other (diced) geometry?

So... let's grab a beer some time.  I'm actually *really* excited to talk about this kind of stuff, but this thread is going to quickly get very long and very off-topic if we head down that road.  If you're curious, though, I recommend taking a look at the [Psychopath blog](https://psychopath.io/).

But the very, very short answer is that I've explored some interesting (and I think worthwhile) approaches in the past, but have ultimately settled on just making life a little harder for the user in favor of a simpler architecture that doesn't create difficult problems around e.g. bidirectional light transport.

**Comment by virtualritz** [comment]
I would love to grab a beer. Not sure about your whereabouts though. Github says Nippon which I used to visit once ever 1–2 years. But with the current situation ...?

I'm also more a TD/user of renderers that a renderer developer. The latter never intrigued me much.

I do have strong opinions nevertheless on some topics; based on being an expert user (as in: an expert is someone who made every mistake possible in their field of expertise). :)

**Comment by bsavery** [comment]
> In any case, as I alluded to in my previous comment, I strongly suspect that in the end I'll just end up using OSL as-is anyway, and find some complementary way to manage physically based color. But I want to play first, and explore other ideas. Psychopath isn't _that_ serious of a project. It's a playground for me to play with ideas that I find interesting.

If I understand, this is exactly what manuka did https://jo.dreggn.org/path-tracing-in-production/2017/talk-jo/ and then samples rgb to spectral when passing it to bxdf parameters.  Makes sense.

**Comment by cessen** [comment]
@bsavery 

Yeah, that was my impression as well.  And I think that solution makes a lot of sense.  The down side is that you can't use other color models with full flexibility in the shading system, then.  So that's part of why I want to explore other things first. :-)

**Comment by cessen** [comment]
@virtualritz 
Yeah, I'm currently in Japan.  I'll be returning to the Seattle area in about a year.  But I was more thinking, e.g., if we end up crossing paths at a conference or something. :-)  Although if you happen to be in the Seattle area, then definitely!

**Comment by cessen** [comment]
Closing this, because I created the issue long before my decision to follow a new architecture.  It's not irrelevant to the new architecture, but when I eventually get back to hacking on Psychopath I'll be focusing on that getting the core up and running.  I'll re-open again if I need to track my thoughts on this later, when I actually work on the shading system.
