### ISSUE TITLE
License on  Blender plugin

### ISSUE THREAD

**Issue by bsavery** [cessen/psychopath#13]
Took a look at your project.  Interesting looking project, and I was interested in learning rust so this seems like a nice way to get a start.

Just one note though.  (and requisite I am not a lawyer warning).  Blender Addons do not actually have to be under the GPL license.  I see the blender addon section is GPL while the rest is MIT license.  I assume you did this because Blender is GPL.  The exact quote from GNU is https://www.gnu.org/licenses/gpl-faq.en.html#GPLAndPlugins "you must license the plug-in under the GPL or a GPL-compatible free software license and distribute it with source code in a GPL-compliant way".  Which is why many Blender addons use the MIT license.  Just saying if you want the whole thing to be MIT license you can.

**Comment by cessen** [comment]
Thanks for the note!

I'm also not a lawyer, but my understanding is that even though addons can be licensed in other ways, any parts that are calling Blender's Python API would *effectively* be GPL anyway, since they can't practically be used outside of Blender.  So re-licensing Psychoblend under MIT might make sense if there were substantial parts that would be useful outside of Blender... but that's just not the case.  The entire point of Psychoblend is to interact with Blender and its APIs.

(As an aside: I'm also, if anything, considering relicensing Psychopath generally to be under the GPL, and just having some useful parts split out into libraries that are MIT.  Basically following the "applications are GPL, libraries are MIT/BSD/etc." spirit.  But I'm not sure yet.)
